dataset_path : '../fire_dataset/'
models_dir : '/models'

steps_per_epoch : 1000
batch_size : 256
seed : 1
img_width : 224
img_height : 224
epochs : 60
validation_split : 0.15

save_model_path : '/model'