dataset_path : '../dataset_copy/'
models_dir : '/app/models'
test_dir : '/app/test_set'

learning_rate: 0.001
batch_size : 64
seed : 1
img_width : 224
img_height : 224
epochs : 60
validation_split : 0.15

#save_model_path : '/model/'